### ISSUE TITLE
Issues running script

### ISSUE THREAD

**Issue by mathieuboudreau** [martin3141/rats#1]
Thanks for sharing your code! 

I've been trying to run it successfully today, but have encountered a couple of issues.

The first one (which I was able to resolve), was R complaining which CRAN server to download the package pacman from (after I resolved it, the error won't reproduce, so I can't find the exact message). I resolved it by changing this line:

https://github.com/martin3141/rats/blob/0f1228df32b1edceed5ff7149de8451b79ee740c/generate_results.R#L2

to 

```r
if (!require("pacman")) install.packages("pacman", repos='http://cran.us.r-project.org')
```

Now that I got pass that error, when running the script I now get this error:

```
Rscript	generate_results.R
Loading required package: pacman
Error in pul_seq(group, ft, ref, ...) : unused arguments (N, xlim)
Calls: %>% ... eval -> eval -> sim_brain_1h -> sim_basis -> sim_mol
Execution halted
make: *** [main] Error 1
```

Any idea on how to resolve it? I have all the required dependencies you listed on your README.

**Comment by martin3141** [comment]
Thanks for the report, looks like an incompatibility introduced by a fairly recent change. The software is still under heavy development so I'm not too surprised something broke. I'll try and fix over the next few days...

**Comment by mathieuboudreau** [comment]
Ok thanks! No rush, just thought I'd let you know!

**Comment by martin3141** [comment]
I wasn't able to reproduce your issue with the latest development version of the code, so could you try updating to see if it fixes your issue:

`install.packages("devtools")`
`devtools::install_github("martin3141/spant")`

**Comment by martin3141** [comment]
spant v0.15.0 has been released - so I'm assuming this is now resolved until I hear otherwise.
